// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserAPI.Contexts;

#nullable disable

namespace UserAPI.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20251007072924_MyFirstMigration")]
    partial class MyFirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserAPI.Models.BoeingUser", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("UserId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Email");

                    b.HasKey("UserId");

                    b.ToTable("BoeingUsers");
                });

            modelBuilder.Entity("UserAPI.Models.Role", b =>
                {
                    b.Property<long>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("RoleId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("RoleName");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserIdFK");

                    b.HasKey("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("BoeingRoles");
                });

            modelBuilder.Entity("UserAPI.Models.BoeingUser", b =>
                {
                    b.OwnsOne("UserAPI.Models.FullName", "Name", b1 =>
                        {
                            b1.Property<long>("BoeingUserUserId")
                                .HasColumnType("bigint");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("varchar(25)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("varchar(25)")
                                .HasColumnName("LastName");

                            b1.HasKey("BoeingUserUserId");

                            b1.ToTable("BoeingUsers");

                            b1.WithOwner()
                                .HasForeignKey("BoeingUserUserId");
                        });

                    b.Navigation("Name");
                });

            modelBuilder.Entity("UserAPI.Models.Role", b =>
                {
                    b.HasOne("UserAPI.Models.BoeingUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
