apiVersion: v1
kind: Service
metadata:
  name: userservice
  labels:
    app: userservice
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: userapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userapi
spec:
  selector:

    matchLabels:

      app: userapi
  replicas: 1
  template:
    metadata:
      labels:
        app: userapi
        version: v1
    spec:
      containers:
      - name: userapi
        image: eswaribala/boeingblroct2025:userapi
        
        ports:
        - containerPort: 80
        env:

            - name: ASPNETCORE_ENVIRONMENT

              value: DEVELOPMENT

            - name: SQLSERVER_CONNECTIONSTRING1

              value: "Server=host.docker.internal,1403;Database=UserDB;User ID=sa;Password=Vignesh@95!;TrustServerCertificate=true;MultipleActiveResultSets=true"  
        